server.port: 7002
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: none

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  application:
    name: recommendation
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: true
    url: jdbc:postgresql://${RECOMMENDATION_POSTGRES_HOST_AND_PORT}/recommendation-db
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  r2dbc:
    url: r2dbc:postgresql://${RECOMMENDATION_POSTGRES_HOST_AND_PORT}/recommendation-db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      max-create-connection-time: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# Spring Cloud SetUp
spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: recommendations
    group: recommendationsGroup

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: ${KAFKA_HOST}
  defaultBrokerPort: ${KAFKA_PORT}

spring.rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

app.eureka-server: eureka

server.port: 8080

spring:
  liquibase:
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-recommendation-db/recommendation-db
    enabled: true
  r2dbc:
    url: r2dbc:postgresql://postgres-recommendation-db/recommendation-db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

---
spring.config.activate.on-profile: streaming_partitioned

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  partitioned: true
  instanceCount: 2

---
spring.config.activate.on-profile: streaming_instance_0

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  instanceIndex: 0

---
spring.config.activate.on-profile: streaming_instance_1

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  instanceIndex: 1

---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: ${KAFKA_SERVER_BOOTSTRAP}
spring.cloud.stream.kafka.binder.replication-factor: 1
