server.port: 7002
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: none

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/recommendation-db
    password: password
    user: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/recommendation-db
    username: postgres
    password: password
    pool:
      max-create-connection-time: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:postgresql://postgres-recommendation-db/recommendation-db