server.port: 7001
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: create

spring.datasource.hikari.initializationFailTimeout: 60000
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/product-db"
    username: "postgres"
    password: "password"
---
spring.config.activate.on-profile: docker

server.port: 8080