server.port: 7001
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: none

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/product-db
    #  datasource:
    #    url: "jdbc:postgresql://localhost:5432/product-db"
    user: "postgres"
    password: "password"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product-db
    username: postgres
    password: password
    name: product-db
    pool:
      max-create-connection-time: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:postgresql://postgres-product-db/product-db